#!/bin/bash

ESLINT="eslint -c .eslintrc.json --ext .ts"
STAGED_FILES=$(git diff --cached --name-only | grep -E '(.ts)$')
PASS=true

if [ "$STAGED_FILES" = "" ]; then
  exit 0
fi
for FILE in $STAGED_FILES
do
  $ESLINT "$FILE"

  if [[ "$?" == 0 ]]; then
    echo -e "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    echo -e "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

if ! $PASS; then
  echo -e "\033[41mCOMMIT FAILED:\033[0m ESLint failed on staged files. Please check your code and try again. You can run ESLint manually via npm run lint. \n"
  exit 1 # exit with failure status
else
  echo -e "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
