version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler
    volumes:
      - ../postgres:/var/lib/postgresql/data
    ports:
      - 5423:5423

  secheduler_backend:
    image: node:16-alpine
    working_dir: /app
    environment:
      PORT: 8000
      DATABASE_URL: "postgres://postgres:postgres@postgres/scheduler"
      ENV: LOCAL
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: sh -c "yarn install; npx sequelize db:create; yarn run dev"
